name: APSystems
description: Sync Energy dashboards with your APSystems photovoltaic solar panel system
version: 0.0.2
slug: apsystems
init: false
url: https://github.com/J-Phiz/ha-apsystems
image: ghcr.io/j-phiz/ha-apsystems-{arch}
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
hassio_api: true
map:
  - addon_config
options:
  meters:
    - systemId: ''
      ecuId: ''
      name: 'APSystems main residence'
      action: 'sync'
    - systemId: ''
      ecuId: ''
      name: 'APSystems second residence'
      action: 'sync'
  openapi:
    appId: ''
    appSecret: ''
schema:
  meters:
    - systemId: str?
      ecuId: str?
      name: str?
      action: list(sync|reset)
  openapi:
    appId: str?
    appSecret: str?
